version: "3.9"

services:
  api:
    build:
      context: .
    image: katyssha/skypro_hw26
    ports:
      - 80:80
    volumes:
      - ./docker_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: skypro_user
      POSTGRES_PASSWORD: skypro_password
      POSTGRES_DB: skypro_hw
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5