version: "3.9"

services:
  api:
    image: katyssha/skypro_hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    networks:
      - my-net
  pg:
    image: postgres:latest
    networks:
      - my-net
    environment:
      POSTGRES_USER: DB_USER
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
    my-net: