version: "3.9"
services:
  api:
    build:
      context: ../app
    networks:
      - my-network
    ports:
      - 5000:5000
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    networks:
      - my-network
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: flask_app_password
      POSTGRES_DB: flask_app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
networks:
  my-network: